[package]
name = "cpu_code"
version = "0.1.0"
edition = "2024"
publish = ["crates-io"]

[dependencies]
cuda_min = { path = "../../cuda_min", features = ["cudart"] }
[build-dependencies]
cuda_min = { path = "../../cuda_min" }
